version: "3.8"
services:

  postgres_produto:
    restart: always
    image: postgres:10.4
    ports:
      - '5432:5432'
    environment:
         - POSTGRES_PASSWORD=123456
         - POSTGRES_USER=postgres
         - POSTGRES_DB=produtodb
    networks:
        - emp-network

  
  config-server:
    container_name: config-server
    image: valrsilva/config-server:latest
    expose:
        - 8888
    ports:
        - 8888:8888
    networks:
        - emp-network
    volumes:
        - config-repo:/var/lib/config-repo

  eureka-server:
    container_name: eureka-server
    image: valrsilva/eureka-server:latest
    expose:
        - 8761
    ports:
        - 8761:8761
    networks:
        - emp-network

  zuul-server:
    container_name: zuul-server
    image: valrsilva/zuul-server:latest
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    expose:
        - 8184
    ports:
        - 8184:8184
    depends_on:
      - config-server
      - eureka-server
    networks:
        - emp-network

  produto:
    image: valrsilva/produto:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_produto:5432/produtodb
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: produto
      SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS: kafka:9092
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    expose:
      - '8081'
    ports:
      - '8081:8081'
    depends_on:
      - postgres_produto
      - config-server
      - eureka-server
    networks:
      - emp-network

  notificacao:
    image: valrsilva/notificacao:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_notificacao:5432/notificacaodb
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: notificacao
      SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS: kafka:9092
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    expose:
      - '8082'
    ports:
      - '8082:8082'
    depends_on:
      - postgres_notificacao
      - config-server
      - eureka-server
    networks:
      - emp-network

  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2181:2181"
    networks:
      - emp-network

  kafka:
    image: confluentinc/cp-kafka:5.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
    networks:
      - emp-network

  frontend:
    image: valrsilva/webserver:latest
    ports:
      - "8080:80"
    networks:
      - emp-network
    depends_on:
      - produto

networks:
    emp-network:
        driver: bridge
volumes:
    config-repo:
        external: false