version: "3.8"
services:

  postgres:
    restart: always
    image: postgres:10.4
    ports:
      - '5432:5432'
    environment:
         - POSTGRES_PASSWORD=123456
         - POSTGRES_USER=postgres
         - POSTGRES_DB=produtodb
    networks:
        - emp-network

  pgadmin:
    restart: always
    image: dpage/pgadmin4:latest
    ports:
      - '8088:80'
    environment:
       - PGADMIN_DEFAULT_EMAIL=valrsilva@gmail.com
       - PGADMIN_DEFAULT_PASSWORD=123456
    networks:
        - emp-network

networks:
    emp-network:
        driver: bridge

